### ISSUE TITLE
Crystal + ARM

### ISSUE THREAD

**Issue by GrantBirki** [Hadeweka/crystowl-nest#1]
Hey there @Hadeweka! 👋 

I see you have dabbled in `crystal` + `arm` in this repo. Specifically, I see you have done some stuff with Raspberry PIs. I'm actually doing the same at the moment. I built out a new project as an experiment ([source](https://github.com/runwaylab/runway)) and so far it runs on x86_64 linux systems perfectly! However, I'm struggling with `arm64` style systems like my Raspberry Pi 4.

I'm wondering if you know anything more about the state of things with crystal and arm systems. How hard is it to go down this route? Should this even be something worth trying?

My project has a fair amount of [runtime dependencies](https://github.com/runwaylab/runway/blob/1cab2545c8f91ab8f5114f72969990ae5ac1aecd/shard.yml#L15-L33) as well so I'm wondering if that will further complicate things.

**Comment by Hadeweka** [comment]
Sorry, I haven't used Crystal on the Raspberry Pi in years. The information in the `RaspiRun.md` file is probably heavily outdated, too.

You might want to ask your question in one of the Crystal discussion channels (like the forum or discord), I think the people there can provide better help.

**Comment by GrantBirki** [comment]
Thank you! I had no idea there was a Discord so I will join and ask around in there 🙇

**Comment by GrantBirki** [comment]
@Hadeweka update, it was crazy easy to do! https://github.com/runwaylab/runway/pull/17 🚀

**Comment by Hadeweka** [comment]
Glad to hear!
